name: Docker Image CI

on:
  push:
    branches:
      - main

  # FIXME: 해당 event는 테스트를 위해 임시로 넣음 삭제해야함
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get the version
        id: get_version
        run: |
          echo "::set-output name=DATE::$(date +'%Y.%m.%d')"
          echo "::set-output name=TIME::$(date +'%H.%M.%S')"
          echo "::set-output name=HASH::$(git rev-parse --short=4 HEAD)"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ steps.get_version.outputs.DATE }}.${{ steps.get_version.outputs.TIME }}.${{ steps.get_version.outputs.HASH }}